<a href="https://colab.research.google.com/github/myaseir/Blood-Project/blob/main/Pytorchbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [4]:
# using empty
a= torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [7]:
# usin zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using 1
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using Rand
torch.rand(2,3)

tensor([[0.9715, 0.1456, 0.5595],
        [0.6198, 0.8710, 0.8892]])

In [10]:
# if we used rand again the value changes
torch.rand(2,3)

tensor([[0.5594, 0.1342, 0.7813],
        [0.1113, 0.7096, 0.8327]])

In [11]:
# if we want to keep it same we use manual_seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# and if we again run it , the output is same
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])